# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'java-web-jsp/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'java-web-jsp/pom.xml'
    goals: 'install'
    artifactoryResolverService: 'arti-horizons'
    targetResolveReleaseRepo: 'default-maven-virtual'
    targetResolveSnapshotRepo: 'default-maven-virtual'
    artifactoryDeployService: 'arti-horizons'
    targetDeployReleaseRepo: 'ms-java-release'
    targetDeploySnapshotRepo: 'ms-java-snapshots'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'arti-horizons'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'a10071967'

- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'x-ray-horizons'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'a10071967'
    allowFailBuild: true
    vuln: true